### ISSUE TITLE
Binary release

### ISSUE THREAD

**Issue by wxmerkt** [ctu-vras/stamped_msgs#1]
Hi @peci1!
I was just about to create a package with the same name and content and quite glad I found this repository. Do you have any plans on releasing this package to the buildfarm? It would come in quite handy as a default package of stamped message types :-) 

Many thanks,
Wolfgang

**Comment by peci1** [comment]
No. That would go against the principles stated by OSRF e.g. in https://answers.ros.org/question/9715/stamped-std_msgs/ and https://github.com/ros/std_msgs/issues/7 .

I know it's a bit painful, but I'd rather keep the way to these grey-zone messages more complicated (e.g. cloning this package in your workspace instead of just apt-installing it).

**Comment by peci1** [comment]
I added a readme containing a warning that it is not suggested to use this package, but it can be used for quick prototyping.

**Comment by wxmerkt** [comment]
Thank you for the swift response. I was aware of the 2011 post - there still is demonstrated demand for stamped versions of primitive types in debugging, development, and research when the topic name fully specifies the content of the information as is frequently used (and prevents people abusing commonly available message types that have no semantic meaning e.g. `sensor_msgs/JointState` for non-position/velocity/effort quantities because it is a stamped Float64[] - I've observed such across many codebases :disappointed:).

In the past few years, I've noticed that 
(1) people using non-stamped standard messages and plotting against receipt/logging timestamps not realising it's not indicative of when it was sent / the data was sampled/created [especially for systems with high-load or poor network]
and 
(2) non binary release availability of many small custom message packages 

were among the biggest beginner challenges and sources of many bugs (and ill-drawn conclusions) even among seasoned practitioners

**Comment by peci1** [comment]
You can try raising this issue again on discourse.ros.org, maybe things have changed since 2011, and the reality shows this kind of messages is indeed widely needed. But until there is a majority of community and Open Robotics employees vouching for having the stamped messages, I won't release this package in binary form.
